baseURL = "https://vishvAsa.github.io/kannaDa/"
languageCode = "en-us"
title = "ಕನ್ನಡದಲ್ಲಿ ವಿಶ್ವಾಸ-ಟಿಪ್ಪಣಿಗಳು"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/kannaDa/edit/content/"
  contactLink = "https://github.com/vishvAsa/kannaDa/issues/new"
  build_img = "https://github.com/vishvAsa/kannaDa/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/vishvAsa/kannaDa/actions/workflows/build.yml"
  fullSearchURL = "/full_search"
  env = "production"  
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true